# tarql --dedup 1000 circonscriptions.sparql > circonscriptions.ttl
prefix custom: <https://github.com/Ajamelot56/Dana-Senateurs/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix schema: <http://schema.org/>
prefix dbo: <http://dbpedia.org/ontology/>

construct {
  ?circ rdf:type dbo:Settlement ;
    dbo:officialName ?Circonscription ;
    dbo:inseeCode ?code
}
from <file:../csv/ODSEN_GENERAL.csv#encoding=cp1252>
where {
  bind(uri(concat('https://github.com/Ajamelot56/Dana-Senateurs/', ?Code_Circonscription)) as ?circ)
  bind(str(?Code_Circonscription) as ?code)
}
