# tarql --dedup 1000 circonscriptions.sparql > circonscriptions.ttl
prefix custom: <http://localhost/>
prefix rdf: <http://w3c.org/1999/02/22-rdf-syntax-ns#>
prefix schema: <http://schema.org/>
prefix dbo: <http://dbpedia.org/ontology/>

construct {
  ?circ rdf:type dbo:Settlement ;
    dbo:officialName ?Circonscription ;
    dbo:inseeCode ?code
}
from <file:ODSEN_GENERAL.csv#encoding=cp1252>
where {
  bind(uri(concat('http://localhost/', ?Code_Circonscription)) as ?circ)
  bind(str(?Code_Circonscription) as ?code)
}