prefix schema: <http://schema.org/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

construct {
    ?u schema:affiliation [
        rdf:value ?groupe ;
        schema:startDate ?dateD ;
        schema:endDate ?dateF
    ] .
}
from <file:ODSEN_HISTOGROUPES.csv#encoding=cp1252>
where {
    bind (uri(concat('http://localhost/', ?Matricule)) as ?u)
    bind (uri(?Code_du_groupe_politique) as ?groupe)
    bind (strbefore(?Date_de_début_d_appartenance, ' ') as ?dateD)
    bind (strbefore(?Date_de_fin_d_appartenance, ' ') as ?dateF)
}